export interface GraphNode {
  id: string
  label: string
  category: 'calculus' | 'linear-algebra' | 'probability' | 'machine-learning' | 'physics'
  subCategory: string
  description: string
  formula?: string
  x: number // percentage 5 - 95
  y: number // percentage 8 - 92
  size: number
  mastery: number // 0 - 100
  tier: 1 | 2 | 3 // 1: Foundation, 2: Core, 3: Advanced
  prerequisites: string[]
  connectedIds: string[]
  citation: string
  syllabusUnit: string
  keyTakeaway: string
}

export interface GraphEdge {
  id: string
  source: string
  target: string
  type: 'prerequisite' | 'concept' | 'application' | 'mastery'
  strength?: number
}

export interface QAScenario {
  id: string
  question: string
  shortLabel: string
  sourceNodeId: string
  path: string[]
  citation: string
  confidence: number
  sourceHierarchy: string
  answer: string
  keyFormulas: string[]
  prerequisiteInsight: string
}

export const CATEGORY_COLORS: Record<GraphNode['category'], {
  accent: string
  glow: string
  badge: string
  border: string
  text: string
}> = {
  calculus: {
    accent: '#06b6d4',
    glow: 'rgba(6, 182, 212, 0.5)',
    badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    border: 'border-cyan-500/40',
    text: 'text-cyan-400',
  },
  'linear-algebra': {
    accent: '#10b981',
    glow: 'rgba(16, 185, 129, 0.5)',
    badge: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    border: 'border-emerald-500/40',
    text: 'text-emerald-400',
  },
  probability: {
    accent: '#f59e0b',
    glow: 'rgba(245, 158, 11, 0.5)',
    badge: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    border: 'border-amber-500/40',
    text: 'text-amber-400',
  },
  'machine-learning': {
    accent: '#a855f7',
    glow: 'rgba(168, 85, 247, 0.5)',
    badge: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    border: 'border-purple-500/40',
    text: 'text-purple-400',
  },
  physics: {
    accent: '#38bdf8',
    glow: 'rgba(56, 189, 248, 0.5)',
    badge: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
    border: 'border-sky-500/40',
    text: 'text-sky-400',
  },
}

export const GRAPH_NODES: GraphNode[] = [
  // CALCULUS CLUSTER (Central-West)
  {
    id: 'limits',
    label: 'Limits & Continuity',
    category: 'calculus',
    subCategory: 'Foundations',
    description: 'The rigorous mathematical basis describing function behavior as an input nears a boundary or infinity.',
    formula: 'lim_{x \\to c} f(x) = L',
    x: 22,
    y: 28,
    size: 9,
    mastery: 95,
    tier: 1,
    prerequisites: [],
    connectedIds: ['derivatives', 'continuity', 'integrals'],
    citation: 'Engineering Math IV • Unit 1.1 • Stewart §2.2',
    syllabusUnit: 'UNIT I: Foundations of Analysis',
    keyTakeaway: 'The bedrock of infinitesimal calculus without which instantaneous rate of change cannot be defined.',
  },
  {
    id: 'continuity',
    label: 'Continuity & IVT',
    category: 'calculus',
    subCategory: 'Foundations',
    description: 'Guarantees no breaks, jumps, or asymptotes, enabling the Intermediate Value Theorem.',
    formula: 'lim_{x \\to c} f(x) = f(c)',
    x: 15,
    y: 38,
    size: 7,
    mastery: 88,
    tier: 1,
    prerequisites: ['limits'],
    connectedIds: ['limits', 'derivatives'],
    citation: 'Engineering Math IV • Unit 1.2 • Stewart §2.5',
    syllabusUnit: 'UNIT I: Foundations of Analysis',
    keyTakeaway: 'Necessary condition for differentiability over a closed interval.',
  },
  {
    id: 'derivatives',
    label: 'Derivatives',
    category: 'calculus',
    subCategory: 'Differential Calculus',
    description: 'The instantaneous rate of change of a function with respect to one of its variables.',
    formula: "f'(x) = lim_{h \\to 0} [f(x+h) - f(x)] / h",
    x: 28,
    y: 38,
    size: 11,
    mastery: 92,
    tier: 1,
    prerequisites: ['limits', 'continuity'],
    connectedIds: ['limits', 'chain-rule', 'integrals', 'partial-derivatives', 'optimization'],
    citation: 'Engineering Math IV • Unit 2.1 • Stewart §3.1',
    syllabusUnit: 'UNIT II: Differential Calculus',
    keyTakeaway: 'Transforms static geometric secants into instantaneous tangent slopes.',
  },
  {
    id: 'chain-rule',
    label: 'Chain Rule',
    category: 'calculus',
    subCategory: 'Differential Calculus',
    description: 'Computes derivative of composite functions by multiplying internal and external rates of change.',
    formula: "(f \\circ g)'(x) = f'(g(x)) \\cdot g'(x)",
    x: 35,
    y: 30,
    size: 9,
    mastery: 84,
    tier: 2,
    prerequisites: ['derivatives'],
    connectedIds: ['derivatives', 'backprop', 'implicit-diff'],
    citation: 'Engineering Math IV • Unit 2.3 • Stewart §3.4',
    syllabusUnit: 'UNIT II: Differential Calculus',
    keyTakeaway: 'The algorithmic core driving deep neural network backpropagation.',
  },
  {
    id: 'implicit-diff',
    label: 'Implicit Differentiation',
    category: 'calculus',
    subCategory: 'Differential Calculus',
    description: 'Differentiating curves defined implicitly where isolating the dependent variable is intractable.',
    formula: "d/dx [x^2 + y^2 = r^2] \\implies 2x + 2y y' = 0",
    x: 38,
    y: 20,
    size: 6,
    mastery: 72,
    tier: 2,
    prerequisites: ['chain-rule'],
    connectedIds: ['chain-rule', 'related-rates'],
    citation: 'Engineering Math IV • Unit 2.4 • Stewart §3.5',
    syllabusUnit: 'UNIT II: Differential Calculus',
    keyTakeaway: 'Enables calculus along non-function manifolds and level sets.',
  },
  {
    id: 'taylor-series',
    label: 'Taylor & Maclaurin Series',
    category: 'calculus',
    subCategory: 'Analysis',
    description: 'Approximating smooth functions locally through an infinite polynomial expansion of higher derivatives.',
    formula: 'f(x) = \\sum_{n=0}^{\\infty} [f^{(n)}(a)/n!] (x-a)^n',
    x: 44,
    y: 34,
    size: 8,
    mastery: 65,
    tier: 3,
    prerequisites: ['derivatives'],
    connectedIds: ['derivatives', 'loss-landscapes', 'differential-eq'],
    citation: 'Engineering Math IV • Unit 2.6 • Stewart §11.10',
    syllabusUnit: 'UNIT II: Sequences & Series',
    keyTakeaway: 'Allows computers to calculate transcendental functions (sin, exp, log) efficiently.',
  },
  {
    id: 'integrals',
    label: 'Riemann Integrals',
    category: 'calculus',
    subCategory: 'Integral Calculus',
    description: 'Continuous accumulation of infinitesimal slices to calculate areas, volumes, and totals.',
    formula: '\\int_a^b f(x) dx = lim_{n \\to \\infty} \\sum f(x_i^*) \\Delta x',
    x: 26,
    y: 54,
    size: 10,
    mastery: 78,
    tier: 2,
    prerequisites: ['limits', 'derivatives'],
    connectedIds: ['derivatives', 'fundamental-theorem', 'differential-eq', 'continuous-distributions'],
    citation: 'Engineering Math IV • Unit 3.1 • Stewart §5.1',
    syllabusUnit: 'UNIT III: Integral Calculus',
    keyTakeaway: 'Duality inverse to differentiation, unlocking continuous density modeling.',
  },
  {
    id: 'fundamental-theorem',
    label: 'Fundamental Thm of Calculus',
    category: 'calculus',
    subCategory: 'Integral Calculus',
    description: 'Bridges differentiation and integration, showing they are inverse processes.',
    formula: 'd/dx \\int_a^x f(t) dt = f(x)',
    x: 36,
    y: 50,
    size: 9,
    mastery: 80,
    tier: 2,
    prerequisites: ['derivatives', 'integrals'],
    connectedIds: ['integrals', 'derivatives', 'differential-eq'],
    citation: 'Engineering Math IV • Unit 3.2 • Stewart §5.3',
    syllabusUnit: 'UNIT III: Integral Calculus',
    keyTakeaway: 'The central theorem connecting rates of change to total accumulated value.',
  },
  {
    id: 'partial-derivatives',
    label: 'Partial Derivatives',
    category: 'calculus',
    subCategory: 'Multivariable',
    description: 'Rate of change of a multivariable function when all other variables are held strictly constant.',
    formula: '\\partial f / \\partial x_i = lim_{h \\to 0} [f(x_1,...,x_i+h,...) - f] / h',
    x: 48,
    y: 42,
    size: 10,
    mastery: 82,
    tier: 2,
    prerequisites: ['derivatives', 'vectors'],
    connectedIds: ['derivatives', 'gradient-vector', 'hessian', 'optimization'],
    citation: 'Multivariable Calculus • Unit 1.3 • Marsden §2.3',
    syllabusUnit: 'UNIT IV: Multivariable Calculus',
    keyTakeaway: 'Opens single-variable calculus up into multidimensional parameter spaces.',
  },
  {
    id: 'gradient-vector',
    label: 'Gradient Vector (∇f)',
    category: 'calculus',
    subCategory: 'Multivariable',
    description: 'Vector of all first-order partial derivatives pointing in the direction of steepest ascent.',
    formula: '\\nabla f = [\\partial f/\\partial x_1, \\partial f/\\partial x_2, ..., \\partial f/\\partial x_n]^T',
    x: 56,
    y: 40,
    size: 10,
    mastery: 76,
    tier: 2,
    prerequisites: ['partial-derivatives', 'vectors'],
    connectedIds: ['partial-derivatives', 'gradient-descent', 'directional-derivative'],
    citation: 'Multivariable Calculus • Unit 1.4 • Marsden §2.6',
    syllabusUnit: 'UNIT IV: Multivariable Calculus',
    keyTakeaway: 'Defines the compass heading for all modern machine learning optimization algorithms.',
  },
  {
    id: 'differential-eq',
    label: 'Ordinary Differential Eq.',
    category: 'calculus',
    subCategory: 'Dynamics',
    description: 'Equations relating unknown functions to their derivatives, describing dynamical systems in nature.',
    formula: 'dy/dt = ky(1 - y/K)',
    x: 32,
    y: 68,
    size: 8,
    mastery: 55,
    tier: 3,
    prerequisites: ['fundamental-theorem'],
    connectedIds: ['fundamental-theorem', 'integrals', 'laplace'],
    citation: 'Engineering Math IV • Unit 4.1 • Boyce-DiPrima §1.1',
    syllabusUnit: 'UNIT V: Differential Equations',
    keyTakeaway: 'The universal language describing motion, heat, waves, circuits, and populations.',
  },

  // LINEAR ALGEBRA CLUSTER (North-East)
  {
    id: 'vectors',
    label: 'Vector Spaces & Spans',
    category: 'linear-algebra',
    subCategory: 'Linear Foundations',
    description: 'Mathematical objects endowed with vector addition and scalar multiplication axioms.',
    formula: 'v = \\sum_{i=1}^n c_i e_i \\in \\mathbb{R}^n',
    x: 62,
    y: 22,
    size: 10,
    mastery: 90,
    tier: 1,
    prerequisites: [],
    connectedIds: ['matrices', 'partial-derivatives', 'dot-product'],
    citation: 'Linear Algebra • Unit 1.1 • Strang §1.1',
    syllabusUnit: 'UNIT I: Vector Spaces',
    keyTakeaway: 'Geometric arrows generalize into abstract multi-dimensional feature representations.',
  },
  {
    id: 'dot-product',
    label: 'Dot Product & Projections',
    category: 'linear-algebra',
    subCategory: 'Linear Foundations',
    description: 'Measures angle, magnitude, orthogonality, and vector projection between coordinate systems.',
    formula: 'u \\cdot v = \\|u\\| \\|v\\| \\cos(\\theta)',
    x: 72,
    y: 18,
    size: 7,
    mastery: 85,
    tier: 1,
    prerequisites: ['vectors'],
    connectedIds: ['vectors', 'orthogonality', 'cosine-similarity'],
    citation: 'Linear Algebra • Unit 1.2 • Strang §1.2',
    syllabusUnit: 'UNIT I: Vector Spaces',
    keyTakeaway: 'Enables metric distance and angle calculation in abstract n-dimensional hyperspaces.',
  },
  {
    id: 'matrices',
    label: 'Matrix Transformations',
    category: 'linear-algebra',
    subCategory: 'Linear Operators',
    description: 'Rectangular arrays representing linear coordinate transformations between vector spaces.',
    formula: 'T(u + v) = T(u) + T(v), \\quad T(c u) = c T(u)',
    x: 66,
    y: 30,
    size: 11,
    mastery: 84,
    tier: 1,
    prerequisites: ['vectors'],
    connectedIds: ['vectors', 'determinants', 'eigenvalues', 'matrix-rank'],
    citation: 'Linear Algebra • Unit 2.1 • Strang §2.1',
    syllabusUnit: 'UNIT II: Matrix Algebra',
    keyTakeaway: 'Matrices encode how space stretches, rotates, shears, and compresses.',
  },
  {
    id: 'matrix-rank',
    label: 'Rank & Nullity',
    category: 'linear-algebra',
    subCategory: 'Linear Operators',
    description: 'Dimensionality of the column space versus the dimension of solutions mapped to zero.',
    formula: 'dim(Col A) + dim(Null A) = n',
    x: 76,
    y: 28,
    size: 8,
    mastery: 70,
    tier: 2,
    prerequisites: ['matrices'],
    connectedIds: ['matrices', 'determinants', 'svd'],
    citation: 'Linear Algebra • Unit 2.4 • Strang §3.2',
    syllabusUnit: 'UNIT II: Matrix Algebra',
    keyTakeaway: 'Reveals true degrees of freedom and information bottlenecks in datasets.',
  },
  {
    id: 'determinants',
    label: 'Determinants',
    category: 'linear-algebra',
    subCategory: 'Matrix Properties',
    description: 'Scalar value characterizing volume scaling and invertibility of a linear map.',
    formula: '\\det(A) = \\prod \\lambda_i',
    x: 82,
    y: 36,
    size: 8,
    mastery: 75,
    tier: 2,
    prerequisites: ['matrices'],
    connectedIds: ['matrices', 'eigenvalues'],
    citation: 'Linear Algebra • Unit 3.1 • Strang §5.1',
    syllabusUnit: 'UNIT III: Invertibility & Determinants',
    keyTakeaway: 'Zero determinant indicates space collapses into lower dimensions (non-invertible).',
  },
  {
    id: 'eigenvalues',
    label: 'Eigenvalues & Eigenvectors',
    category: 'linear-algebra',
    subCategory: 'Spectral Theory',
    description: 'Special directions where linear transformation acts purely by scalar dilation with no rotation.',
    formula: 'A v = \\lambda v',
    x: 72,
    y: 44,
    size: 11,
    mastery: 68,
    tier: 3,
    prerequisites: ['matrices', 'determinants'],
    connectedIds: ['matrices', 'determinants', 'svd', 'pca'],
    citation: 'Linear Algebra • Unit 4.1 • Strang §6.1',
    syllabusUnit: 'UNIT IV: Spectral Theory',
    keyTakeaway: 'Uncovers the natural vibration modes and persistent axes of complex systems.',
  },
  {
    id: 'orthogonality',
    label: 'Orthogonality & Gram-Schmidt',
    category: 'linear-algebra',
    subCategory: 'Subspaces',
    description: 'Perpendicular subspaces where dot products equal zero, yielding stable orthonormal bases.',
    formula: 'Q^T Q = I',
    x: 84,
    y: 22,
    size: 7,
    mastery: 64,
    tier: 2,
    prerequisites: ['dot-product'],
    connectedIds: ['dot-product', 'svd'],
    citation: 'Linear Algebra • Unit 3.3 • Strang §4.4',
    syllabusUnit: 'UNIT III: Orthogonality',
    keyTakeaway: 'Eliminates numerical error in high-dimensional matrix factorization.',
  },
  {
    id: 'svd',
    label: 'Singular Value Decomposition (SVD)',
    category: 'linear-algebra',
    subCategory: 'Matrix Factorization',
    description: 'Decomposes ANY matrix into rotation, scaling along orthogonal axes, and final rotation.',
    formula: 'A = U \\Sigma V^T',
    x: 80,
    y: 52,
    size: 10,
    mastery: 60,
    tier: 3,
    prerequisites: ['eigenvalues', 'orthogonality', 'matrix-rank'],
    connectedIds: ['eigenvalues', 'pca', 'embeddings'],
    citation: 'Linear Algebra • Unit 5.2 • Strang §7.1',
    syllabusUnit: 'UNIT V: SVD & Applications',
    keyTakeaway: 'The crown jewel of linear algebra: optimal low-rank matrix approximation.',
  },

  // PROBABILITY & STATISTICS CLUSTER (South-West)
  {
    id: 'sample-space',
    label: 'Sample Space & Axioms',
    category: 'probability',
    subCategory: 'Probability Foundations',
    description: 'The set of all possible outcomes and Kolmogorov probability axioms governing measure.',
    formula: 'P(\\Omega) = 1, \\quad P(A \\cup B) = P(A) + P(B)',
    x: 18,
    y: 66,
    size: 8,
    mastery: 92,
    tier: 1,
    prerequisites: [],
    connectedIds: ['conditional-prob', 'random-variables'],
    citation: 'Probability & Statistics • Unit 1.1 • Ross §2.1',
    syllabusUnit: 'UNIT I: Probability Foundations',
    keyTakeaway: 'Forms the rigorous axiomatic boundary of uncertain reasoning.',
  },
  {
    id: 'conditional-prob',
    label: 'Conditional Probability',
    category: 'probability',
    subCategory: 'Conditioning',
    description: 'Updated probability of event A given that condition B has observed to occur.',
    formula: 'P(A|B) = P(A \\cap B) / P(B)',
    x: 24,
    y: 76,
    size: 9,
    mastery: 86,
    tier: 1,
    prerequisites: ['sample-space'],
    connectedIds: ['sample-space', 'bayes-theorem', 'independence'],
    citation: 'Probability & Statistics • Unit 1.3 • Ross §3.2',
    syllabusUnit: 'UNIT I: Conditioning & Bayes',
    keyTakeaway: 'Transforms unconditional prior beliefs into updated conditional evidence.',
  },
  {
    id: 'bayes-theorem',
    label: "Bayes' Theorem",
    category: 'probability',
    subCategory: 'Inference',
    description: 'Calculates posterior probability by inverting conditional dependencies using likelihood and prior.',
    formula: 'P(\\theta|D) = \\frac{P(D|\\theta) P(\\theta)}{P(D)}',
    x: 36,
    y: 80,
    size: 11,
    mastery: 80,
    tier: 2,
    prerequisites: ['conditional-prob'],
    connectedIds: ['conditional-prob', 'mle', 'active-inference'],
    citation: 'Probability & Statistics • Unit 2.1 • Ross §3.6',
    syllabusUnit: 'UNIT II: Bayesian Inference',
    keyTakeaway: 'The mathematical equation for learning from new evidence.',
  },
  {
    id: 'random-variables',
    label: 'Random Variables & Expectation',
    category: 'probability',
    subCategory: 'Distributions',
    description: 'Functions mapping outcomes to real numbers, characterized by expected value and variance.',
    formula: '\\mathbb{E}[X] = \\int x f_X(x) dx, \\quad \\text{Var}(X) = \\mathbb{E}[(X - \\mu)^2]',
    x: 18,
    y: 84,
    size: 8,
    mastery: 78,
    tier: 1,
    prerequisites: ['sample-space'],
    connectedIds: ['sample-space', 'continuous-distributions', 'mle'],
    citation: 'Probability & Statistics • Unit 3.1 • Ross §4.1',
    syllabusUnit: 'UNIT III: Random Variables',
    keyTakeaway: 'Translates event outcomes into quantitative mathematical variables.',
  },
  {
    id: 'continuous-distributions',
    label: 'Continuous Distributions (Normal)',
    category: 'probability',
    subCategory: 'Distributions',
    description: 'Probability density functions including the Gaussian / Normal bell curve and Central Limit Theorem.',
    formula: '\\mathcal{N}(x; \\mu, \\sigma^2) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}',
    x: 30,
    y: 88,
    size: 9,
    mastery: 72,
    tier: 2,
    prerequisites: ['random-variables', 'integrals'],
    connectedIds: ['random-variables', 'integrals', 'mle'],
    citation: 'Probability & Statistics • Unit 3.4 • Ross §5.4',
    syllabusUnit: 'UNIT III: Continuous Densities',
    keyTakeaway: 'Due to Central Limit Theorem, sums of independent random variables converge to Gaussian.',
  },
  {
    id: 'mle',
    label: 'Maximum Likelihood Estimation',
    category: 'probability',
    subCategory: 'Statistical Learning',
    description: 'Finds parameter values maximizing the probability of having observed the training sample.',
    formula: '\\hat{\\theta}_{MLE} = \\arg\\max_\\theta \\sum_{i=1}^N \\log P(x_i | \\theta)',
    x: 44,
    y: 84,
    size: 10,
    mastery: 65,
    tier: 3,
    prerequisites: ['continuous-distributions', 'bayes-theorem'],
    connectedIds: ['continuous-distributions', 'bayes-theorem', 'loss-landscapes'],
    citation: 'Statistical Inference • Unit 4.2 • Casella-Berger §7.2',
    syllabusUnit: 'UNIT IV: Parameter Estimation',
    keyTakeaway: 'Derives the standard cross-entropy and mean squared error loss functions.',
  },

  // MACHINE LEARNING & OPTIMIZATION CLUSTER (Center-East & South-East)
  {
    id: 'optimization',
    label: 'Convex Optimization',
    category: 'machine-learning',
    subCategory: 'Optimization',
    description: 'Minimizing objective functions with local minima guaranteed to be global minima.',
    formula: 'f(\\alpha x + (1-\\alpha)y) \\le \\alpha f(x) + (1-\\alpha) f(y)',
    x: 50,
    y: 56,
    size: 9,
    mastery: 70,
    tier: 2,
    prerequisites: ['partial-derivatives', 'derivatives'],
    connectedIds: ['partial-derivatives', 'gradient-descent', 'hessian'],
    citation: 'Optimization Theory • Unit 1.2 • Boyd §3.1',
    syllabusUnit: 'UNIT I: Convex Sets & Functions',
    keyTakeaway: 'Guarantees efficient polynomial-time convergence to globally optimal parameters.',
  },
  {
    id: 'hessian',
    label: 'Hessian Matrix & Curvature',
    category: 'machine-learning',
    subCategory: 'Second-Order Methods',
    description: 'Matrix of second-order partial derivatives describing surface curvature and saddle points.',
    formula: 'H_{i,j} = \\frac{\\partial^2 f}{\\partial x_i \\partial x_j}',
    x: 58,
    y: 52,
    size: 8,
    mastery: 58,
    tier: 3,
    prerequisites: ['partial-derivatives', 'matrices'],
    connectedIds: ['partial-derivatives', 'optimization', 'gradient-descent'],
    citation: 'Multivariable Optimization • Unit 2.2 • Boyd §3.2',
    syllabusUnit: 'UNIT II: Second-Order Curvature',
    keyTakeaway: 'Allows Newton-Raphson quadratic convergence and saddle point diagnostics.',
  },
  {
    id: 'gradient-descent',
    label: 'Gradient Descent (SGD)',
    category: 'machine-learning',
    subCategory: 'Optimization',
    description: 'Iterative first-order optimization algorithm stepping opposite the gradient vector.',
    formula: '\\theta_{t+1} = \\theta_t - \\eta \\nabla_\\theta L(\\theta_t)',
    x: 64,
    y: 60,
    size: 12,
    mastery: 75,
    tier: 2,
    prerequisites: ['gradient-vector', 'optimization'],
    connectedIds: ['gradient-vector', 'optimization', 'backprop', 'loss-landscapes'],
    citation: 'Deep Learning Theory • Unit 2.1 • Goodfellow §4.3',
    syllabusUnit: 'UNIT II: Optimization Algorithms',
    keyTakeaway: 'The workhorse engine training every modern Large Language Model.',
  },
  {
    id: 'loss-landscapes',
    label: 'Loss Surfaces & Minima',
    category: 'machine-learning',
    subCategory: 'Loss Landscapes',
    description: 'High-dimensional geometry of loss functions exhibiting saddle points, plateaus, and valleys.',
    formula: 'L(w) = \\frac{1}{N} \\sum \\mathcal{L}(f_w(x_i), y_i)',
    x: 54,
    y: 72,
    size: 8,
    mastery: 60,
    tier: 3,
    prerequisites: ['gradient-descent', 'mle', 'taylor-series'],
    connectedIds: ['gradient-descent', 'mle', 'backprop'],
    citation: 'Deep Learning Theory • Unit 3.2 • Goodfellow §8.2',
    syllabusUnit: 'UNIT III: High-Dimensional Loss Geometry',
    keyTakeaway: 'Visualizes why overparameterized neural networks escape non-convex traps.',
  },
  {
    id: 'backprop',
    label: 'Backpropagation Algorithm',
    category: 'machine-learning',
    subCategory: 'Deep Learning',
    description: 'Reverse-mode automatic differentiation applying chain rule backward through computational graphs.',
    formula: '\\frac{\\partial L}{\\partial w_{ij}} = \\delta_j a_i = \\frac{\\partial L}{\\partial z_j} \\frac{\\partial z_j}{\\partial w_{ij}}',
    x: 66,
    y: 74,
    size: 11,
    mastery: 74,
    tier: 3,
    prerequisites: ['chain-rule', 'gradient-descent', 'matrices'],
    connectedIds: ['chain-rule', 'gradient-descent', 'attention'],
    citation: 'Deep Learning Architecture • Unit 3.1 • Goodfellow §6.5',
    syllabusUnit: 'UNIT III: Computational Graphs',
    keyTakeaway: 'Computes gradients for billions of parameters in O(N) linear compute time.',
  },
  {
    id: 'pca',
    label: 'Principal Component Analysis',
    category: 'machine-learning',
    subCategory: 'Dimensionality Reduction',
    description: 'Orthogonal transformation projecting data onto principal axes of maximal variance.',
    formula: 'X_{proj} = X V_k, \\quad \\Sigma = \\frac{1}{n} X^T X',
    x: 82,
    y: 66,
    size: 9,
    mastery: 66,
    tier: 3,
    prerequisites: ['eigenvalues', 'svd'],
    connectedIds: ['eigenvalues', 'svd', 'embeddings'],
    citation: 'Pattern Recognition • Unit 4.1 • Bishop §12.1',
    syllabusUnit: 'UNIT IV: Dimensionality Reduction',
    keyTakeaway: 'Compresses thousands of features down into principal explanatory coordinates.',
  },
  {
    id: 'embeddings',
    label: 'Vector Embeddings',
    category: 'machine-learning',
    subCategory: 'Representation Learning',
    description: 'Continuous low-dimensional vector representations capturing semantic relationships and analogy.',
    formula: '\\text{sim}(u, v) = \\frac{u \\cdot v}{\\|u\\| \\|v\\|}',
    x: 78,
    y: 78,
    size: 10,
    mastery: 70,
    tier: 3,
    prerequisites: ['pca', 'dot-product', 'svd'],
    connectedIds: ['pca', 'dot-product', 'attention'],
    citation: 'Representation Learning • Unit 5.1 • Jurafsky §6.3',
    syllabusUnit: 'UNIT V: Semantic Vector Spaces',
    keyTakeaway: 'Allows computers to calculate meaning and reasoning as geometric vector algebra.',
  },
  {
    id: 'attention',
    label: 'Transformer Attention Mechanism',
    category: 'machine-learning',
    subCategory: 'Foundational Models',
    description: 'Dynamic contextual weighting of tokens via Query, Key, and Value dot-product compatibility.',
    formula: '\\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{Q K^T}{\\sqrt{d_k}}\\right) V',
    x: 74,
    y: 88,
    size: 12,
    mastery: 62,
    tier: 3,
    prerequisites: ['backprop', 'embeddings', 'matrices'],
    connectedIds: ['backprop', 'embeddings'],
    citation: 'Advanced Architecture • Unit 6.1 • Vaswani et al. (2017)',
    syllabusUnit: 'UNIT VI: Attention & Transformers',
    keyTakeaway: 'Permits models to route information dynamically across arbitrary sequence lengths.',
  },

  // PHYSICS & DYNAMICS BRIDGE (Center-North & Outer Edge)
  {
    id: 'vector-fields',
    label: 'Vector Fields & Flux',
    category: 'physics',
    subCategory: 'Field Theory',
    description: 'Assignment of a vector to each point in Euclidean space, modeling fluid flows and electromagnetism.',
    formula: '\\mathbf{F}(x,y,z) = P\\mathbf{i} + Q\\mathbf{j} + R\\mathbf{k}',
    x: 48,
    y: 16,
    size: 7,
    mastery: 52,
    tier: 2,
    prerequisites: ['vectors', 'partial-derivatives'],
    connectedIds: ['vectors', 'divergence-curl'],
    citation: 'Field Dynamics • Unit 1.1 • Griffiths §1.2',
    syllabusUnit: 'UNIT I: Multivariable Fields',
    keyTakeaway: 'Bridges multivariable calculus into physical flow and force fields.',
  },
  {
    id: 'divergence-curl',
    label: 'Divergence & Curl',
    category: 'physics',
    subCategory: 'Field Theory',
    description: 'Measures source density (expansion) and circulation (vorticity) of vector fields.',
    formula: '\\nabla \\cdot \\mathbf{F}, \\quad \\nabla \\times \\mathbf{F}',
    x: 36,
    y: 12,
    size: 7,
    mastery: 48,
    tier: 3,
    prerequisites: ['vector-fields', 'partial-derivatives'],
    connectedIds: ['vector-fields'],
    citation: 'Electrodynamics • Unit 2.1 • Griffiths §1.3',
    syllabusUnit: 'UNIT II: Maxwell Foundations',
    keyTakeaway: 'The microscopic differential operators composing Maxwell’s equations of light.',
  },
  {
    id: 'laplace',
    label: 'Laplace Transform',
    category: 'physics',
    subCategory: 'Integral Transforms',
    description: 'Converts time-domain differential equations into algebraic frequency-domain problems.',
    formula: '\\mathcal{L}\\{f(t)\\} = \\int_0^\\infty e^{-st} f(t) dt',
    x: 20,
    y: 50,
    size: 8,
    mastery: 50,
    tier: 3,
    prerequisites: ['differential-eq', 'integrals'],
    connectedIds: ['differential-eq', 'integrals'],
    citation: 'Signals & Systems • Unit 3.1 • Oppenheim §9.1',
    syllabusUnit: 'UNIT III: Transform Methods',
    keyTakeaway: 'Transforms difficult calculus equations into elementary high-school algebra.',
  }
]

export const GRAPH_EDGES: GraphEdge[] = [
  // Calculus core edges
  { id: 'e1', source: 'limits', target: 'continuity', type: 'prerequisite', strength: 1 },
  { id: 'e2', source: 'limits', target: 'derivatives', type: 'prerequisite', strength: 1 },
  { id: 'e3', source: 'continuity', target: 'derivatives', type: 'concept', strength: 0.8 },
  { id: 'e4', source: 'derivatives', target: 'chain-rule', type: 'prerequisite', strength: 1 },
  { id: 'e5', source: 'chain-rule', target: 'implicit-diff', type: 'application', strength: 0.7 },
  { id: 'e6', source: 'derivatives', target: 'taylor-series', type: 'concept', strength: 0.8 },
  { id: 'e7', source: 'limits', target: 'integrals', type: 'prerequisite', strength: 1 },
  { id: 'e8', source: 'derivatives', target: 'fundamental-theorem', type: 'prerequisite', strength: 1 },
  { id: 'e9', source: 'integrals', target: 'fundamental-theorem', type: 'prerequisite', strength: 1 },
  { id: 'e10', source: 'fundamental-theorem', target: 'differential-eq', type: 'concept', strength: 0.9 },
  { id: 'e11', source: 'derivatives', target: 'partial-derivatives', type: 'prerequisite', strength: 1 },
  { id: 'e12', source: 'vectors', target: 'partial-derivatives', type: 'prerequisite', strength: 0.9 },
  { id: 'e13', source: 'partial-derivatives', target: 'gradient-vector', type: 'prerequisite', strength: 1 },
  { id: 'e14', source: 'partial-derivatives', target: 'optimization', type: 'application', strength: 0.9 },
  { id: 'e15', source: 'partial-derivatives', target: 'hessian', type: 'concept', strength: 0.85 },

  // Linear algebra edges
  { id: 'e16', source: 'vectors', target: 'dot-product', type: 'prerequisite', strength: 1 },
  { id: 'e17', source: 'vectors', target: 'matrices', type: 'prerequisite', strength: 1 },
  { id: 'e18', source: 'matrices', target: 'matrix-rank', type: 'concept', strength: 0.8 },
  { id: 'e19', source: 'matrices', target: 'determinants', type: 'prerequisite', strength: 0.9 },
  { id: 'e20', source: 'matrices', target: 'eigenvalues', type: 'prerequisite', strength: 1 },
  { id: 'e21', source: 'determinants', target: 'eigenvalues', type: 'prerequisite', strength: 0.8 },
  { id: 'e22', source: 'dot-product', target: 'orthogonality', type: 'prerequisite', strength: 0.9 },
  { id: 'e23', source: 'eigenvalues', target: 'svd', type: 'prerequisite', strength: 1 },
  { id: 'e24', source: 'orthogonality', target: 'svd', type: 'concept', strength: 0.8 },
  { id: 'e25', source: 'matrix-rank', target: 'svd', type: 'concept', strength: 0.7 },

  // Probability edges
  { id: 'e26', source: 'sample-space', target: 'conditional-prob', type: 'prerequisite', strength: 1 },
  { id: 'e27', source: 'conditional-prob', target: 'bayes-theorem', type: 'prerequisite', strength: 1 },
  { id: 'e28', source: 'sample-space', target: 'random-variables', type: 'prerequisite', strength: 1 },
  { id: 'e29', source: 'random-variables', target: 'continuous-distributions', type: 'concept', strength: 0.9 },
  { id: 'e30', source: 'integrals', target: 'continuous-distributions', type: 'prerequisite', strength: 0.85 },
  { id: 'e31', source: 'continuous-distributions', target: 'mle', type: 'application', strength: 0.8 },
  { id: 'e32', source: 'bayes-theorem', target: 'mle', type: 'concept', strength: 0.75 },

  // Machine Learning synthesis edges
  { id: 'e33', source: 'gradient-vector', target: 'gradient-descent', type: 'prerequisite', strength: 1 },
  { id: 'e34', source: 'optimization', target: 'gradient-descent', type: 'concept', strength: 0.9 },
  { id: 'e35', source: 'hessian', target: 'gradient-descent', type: 'application', strength: 0.7 },
  { id: 'e36', source: 'gradient-descent', target: 'loss-landscapes', type: 'concept', strength: 0.8 },
  { id: 'e37', source: 'chain-rule', target: 'backprop', type: 'prerequisite', strength: 1 },
  { id: 'e38', source: 'matrices', target: 'backprop', type: 'prerequisite', strength: 0.8 },
  { id: 'e39', source: 'gradient-descent', target: 'backprop', type: 'concept', strength: 0.9 },
  { id: 'e40', source: 'svd', target: 'pca', type: 'prerequisite', strength: 1 },
  { id: 'e41', source: 'eigenvalues', target: 'pca', type: 'concept', strength: 0.8 },
  { id: 'e42', source: 'pca', target: 'embeddings', type: 'application', strength: 0.85 },
  { id: 'e43', source: 'dot-product', target: 'embeddings', type: 'concept', strength: 0.8 },
  { id: 'e44', source: 'backprop', target: 'attention', type: 'prerequisite', strength: 0.9 },
  { id: 'e45', source: 'embeddings', target: 'attention', type: 'prerequisite', strength: 0.95 },
  { id: 'e46', source: 'matrices', target: 'attention', type: 'concept', strength: 0.8 },

  // Physics & Field bridges
  { id: 'e47', source: 'vectors', target: 'vector-fields', type: 'prerequisite', strength: 0.9 },
  { id: 'e48', source: 'partial-derivatives', target: 'vector-fields', type: 'prerequisite', strength: 0.85 },
  { id: 'e49', source: 'vector-fields', target: 'divergence-curl', type: 'prerequisite', strength: 1 },
  { id: 'e50', source: 'differential-eq', target: 'laplace', type: 'prerequisite', strength: 0.85 }
]

export const QA_SCENARIOS: QAScenario[] = [
  {
    id: 'chain-rule-qa',
    shortLabel: 'Chain Rule Mechanics',
    question: 'Why does the chain rule work for composite functions?',
    sourceNodeId: 'chain-rule',
    path: ['limits', 'derivatives', 'chain-rule'],
    citation: 'Engineering Math IV • Unit 2.3 • Stewart §3.4',
    confidence: 99.8,
    sourceHierarchy: 'CALCULUS → DIFFERENTIAL CALCULUS → CHAIN RULE',
    answer: 'The chain rule computes the rate of change of a composite function f(g(x)) by multiplying the sensitivity of the outer function with the sensitivity of the inner function. If z = f(y) and y = g(x), then when x nudges by Δx, y changes by approximately g\'(x)Δx. This change in y in turn causes z to change by f\'(y)Δy = f\'(g(x)) · g\'(x)Δx. In the infinitesimal limit as Δx → 0, this cancellation yields (dz/dy) · (dy/dx) = dz/dx.',
    keyFormulas: [
      "(f \\circ g)'(x) = f'(g(x)) \\cdot g'(x)",
      "\\frac{dz}{dx} = \\frac{dz}{dy} \\cdot \\frac{dy}{dx}"
    ],
    prerequisiteInsight: 'Grounded in the limit definition of derivatives; serves as the mathematical pillar behind neural network backpropagation.'
  },
  {
    id: 'gradient-descent-qa',
    shortLabel: 'Gradient Descent & Partial Derivatives',
    question: 'How does Gradient Descent use Partial Derivatives to minimize loss?',
    sourceNodeId: 'gradient-descent',
    path: ['vectors', 'partial-derivatives', 'gradient-vector', 'optimization', 'gradient-descent'],
    citation: 'Deep Learning Theory • Unit 2.1 • Goodfellow §4.3',
    confidence: 99.4,
    sourceHierarchy: 'MULTIVARIABLE CALCULUS → GRADIENT VECTOR → GRADIENT DESCENT',
    answer: 'The gradient vector ∇L bundles every first-order partial derivative ∂L/∂w_i into a single dimensional vector. Mathematically, ∇L always points in the exact direction of steepest slope increase across the multi-dimensional parameter surface. By taking negative steps of scaled magnitude -η ∇L, the parameters w iteratively descend toward the nearest local or global minimum on the loss manifold.',
    keyFormulas: [
      "\\nabla L(w) = \\left[ \\frac{\\partial L}{\\partial w_1}, \\frac{\\partial L}{\\partial w_2}, \\dots, \\frac{\\partial L}{\\partial w_n} \\right]^T",
      "w_{t+1} = w_t - \\eta \\nabla L(w_t)"
    ],
    prerequisiteInsight: 'Relies directly on directional derivatives and vector projection to guarantee downward trajectory.'
  },
  {
    id: 'bayes-theorem-qa',
    shortLabel: "Bayes' Theorem Inference",
    question: 'How does Bayes\' Theorem update prior beliefs with observed evidence?',
    sourceNodeId: 'bayes-theorem',
    path: ['sample-space', 'conditional-prob', 'bayes-theorem'],
    citation: 'Probability & Statistics • Unit 2.1 • Ross §3.6',
    confidence: 99.1,
    sourceHierarchy: 'PROBABILITY → CONDITIONAL PROBABILITY → BAYES\' THEOREM',
    answer: 'Bayes\' Theorem provides the exact formula for rational belief updating. Given a prior probability P(θ) for a hypothesis θ and observing data D, the posterior probability P(θ|D) equals the prior multiplied by the likelihood P(D|θ) of observing that data under the hypothesis, normalized by the marginal probability P(D). It prevents common reasoning fallacies like base-rate neglect.',
    keyFormulas: [
      "P(\\theta | D) = \\frac{P(D | \\theta) \\cdot P(\\theta)}{P(D)}",
      "\\text{Posterior} \\propto \\text{Likelihood} \\times \\text{Prior}"
    ],
    prerequisiteInsight: 'Direct algebraic consequence of Kolmogorov’s definition of conditional probability over intersecting sample spaces.'
  },
  {
    id: 'eigenvalues-svd-qa',
    shortLabel: 'Eigenvalues in SVD & Compression',
    question: 'Why are Eigenvalues and Eigenvectors fundamental to SVD and PCA?',
    sourceNodeId: 'svd',
    path: ['vectors', 'matrices', 'determinants', 'eigenvalues', 'orthogonality', 'svd'],
    citation: 'Linear Algebra • Unit 5.2 • Strang §7.1',
    confidence: 99.6,
    sourceHierarchy: 'LINEAR ALGEBRA → SPECTRAL THEORY → SINGULAR VALUE DECOMPOSITION',
    answer: 'Eigenvectors reveal the natural orthogonal axes along which a linear transformation acts as pure stretching without rotation. Singular Value Decomposition (SVD) generalizes this to rectangular non-square matrices A by finding the eigenvalues of the symmetric Gram matrices A^T A and A A^T. The singular values σ_i are the square roots of these eigenvalues, quantifying the energy distribution along principal axes.',
    keyFormulas: [
      "A v_i = \\lambda_i v_i",
      "A = U \\Sigma V^T, \\quad \\sigma_i = \\sqrt{\\lambda_i(A^T A)}"
    ],
    prerequisiteInsight: 'Enables optimal low-rank matrix approximation (Eckart–Young–Mirsky theorem) used in data compression and LLM embeddings.'
  }
]
